### ISSUE TITLE
New Logo Proposal

### ISSUE THREAD

**Issue by CallMeFib3r** [NAJMUS7834/SensorMusicPlayer#2]
Hi there @NAJMUS7834,
I decided to put together a brand new logo for your project. 
For this logo I combined an old school music disc with a minimalist sensor.
![sensor music player](https://user-images.githubusercontent.com/37731582/38829406-35784b68-41b9-11e8-9cf9-2eb7d8e21744.png)

I hope you like the design and if you do I will send you all of the files.

**Comment by NAJMUS7834** [comment]
OK great!

**Comment by CallMeFib3r** [comment]
Glad you like it! Here are the files associated with the logo. Everything is included (editable files, fonts ready to go png's,...)
[https://drive.google.com/drive/folders/1Rg6QLr4UBb0LkyhfIgWHH1D964TbNP4a?usp=sharing](url)

**Comment by NAJMUS7834** [comment]
Very impressive thanks a lot. But I have done this for my college project.
